language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.6"

cache:
  directories:
  - test_tmp

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    
    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy matplotlib scipy
    - source activate test-environment
    - yes | python setup.py install
    - conda install -y -q -c https://conda.anaconda.org/bcbio pysam
    - pip install coveralls

before_script:
  # Ensure tags are available on the cloned repository
  - git fetch --tags --depth=50

  # Start xvfb
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python test/Simulate_HiC.py ; fi

  - cd test; ls -l *; if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then bash test_meta_waffle.sh; cd - ; fi
  - python -m unittest meta_waffle.test.test_all
  - coverage run -m metawaffle.test.test_all

after_success:
  - coveralls

branches:
  only:
    - master
#     - "3.0"
#     - "2.3"
